package com.nimbledroid.demo.dagger2;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.util.Log;

import com.demo.dagger2.R;
import com.nimbledroid.demo.dagger2.manager.TestManager;
import com.nimbledroid.demo.dagger2.manager.TestManager10;
import com.nimbledroid.demo.dagger2.manager.TestManager11;
import com.nimbledroid.demo.dagger2.manager.TestManager12;
import com.nimbledroid.demo.dagger2.manager.TestManager13;
import com.nimbledroid.demo.dagger2.manager.TestManager14;
import com.nimbledroid.demo.dagger2.manager.TestManager15;
import com.nimbledroid.demo.dagger2.manager.TestManager2;
import com.nimbledroid.demo.dagger2.manager.TestManager3;
import com.nimbledroid.demo.dagger2.manager.TestManager4;
import com.nimbledroid.demo.dagger2.manager.TestManager5;
import com.nimbledroid.demo.dagger2.manager.TestManager6;
import com.nimbledroid.demo.dagger2.manager.TestManager7;
import com.nimbledroid.demo.dagger2.manager.TestManager8;
import com.nimbledroid.demo.dagger2.manager.TestManager9;
import com.nimbledroid.demo.dagger2.module.Dagger2Module;
import com.nimbledroid.demo.dagger2.test.Test1;
import com.nimbledroid.demo.dagger2.test.Test10;
import com.nimbledroid.demo.dagger2.test.Test11;
import com.nimbledroid.demo.dagger2.test.Test12;
import com.nimbledroid.demo.dagger2.test.Test13;
import com.nimbledroid.demo.dagger2.test.Test14;
import com.nimbledroid.demo.dagger2.test.Test15;
import com.nimbledroid.demo.dagger2.test.Test16;
import com.nimbledroid.demo.dagger2.test.Test17;
import com.nimbledroid.demo.dagger2.test.Test18;
import com.nimbledroid.demo.dagger2.test.Test19;
import com.nimbledroid.demo.dagger2.test.Test2;
import com.nimbledroid.demo.dagger2.test.Test20;
import com.nimbledroid.demo.dagger2.test.Test21;
import com.nimbledroid.demo.dagger2.test.Test22;
import com.nimbledroid.demo.dagger2.test.Test23;
import com.nimbledroid.demo.dagger2.test.Test24;
import com.nimbledroid.demo.dagger2.test.Test25;
import com.nimbledroid.demo.dagger2.test.Test26;
import com.nimbledroid.demo.dagger2.test.Test27;
import com.nimbledroid.demo.dagger2.test.Test28;
import com.nimbledroid.demo.dagger2.test.Test29;
import com.nimbledroid.demo.dagger2.test.Test3;
import com.nimbledroid.demo.dagger2.test.Test30;
import com.nimbledroid.demo.dagger2.test.Test31;
import com.nimbledroid.demo.dagger2.test.Test32;
import com.nimbledroid.demo.dagger2.test.Test33;
import com.nimbledroid.demo.dagger2.test.Test34;
import com.nimbledroid.demo.dagger2.test.Test35;
import com.nimbledroid.demo.dagger2.test.Test36;
import com.nimbledroid.demo.dagger2.test.Test37;
import com.nimbledroid.demo.dagger2.test.Test38;
import com.nimbledroid.demo.dagger2.test.Test39;
import com.nimbledroid.demo.dagger2.test.Test4;
import com.nimbledroid.demo.dagger2.test.Test40;
import com.nimbledroid.demo.dagger2.test.Test5;
import com.nimbledroid.demo.dagger2.test.Test6;
import com.nimbledroid.demo.dagger2.test.Test7;
import com.nimbledroid.demo.dagger2.test.Test8;
import com.nimbledroid.demo.dagger2.test.Test9;

import javax.inject.Inject;

public class MainActivity extends AppCompatActivity {

    @Inject Test1 mTest1;
    @Inject Test2 mTest2;
    @Inject Test3 mTest3;
    @Inject Test4 mTest4;
    @Inject Test5 mTest5;
    @Inject Test6 mTest6;
    @Inject Test7 mTest7;
    @Inject Test8 mTest8;
    @Inject Test9 mTest9;
    @Inject Test10 mTest10;
    @Inject Test11 mTest11;
    @Inject Test12 mTest12;
    @Inject Test13 mTest13;
    @Inject Test14 mTest14;
    @Inject Test15 mTest15;
    @Inject Test16 mTest16;
    @Inject Test17 mTest17;
    @Inject Test18 mTest18;
    @Inject Test19 mTest19;
    @Inject Test20 mTest20;
    @Inject Test21 mTest21;
    @Inject Test22 mTest22;
    @Inject Test23 mTest23;
    @Inject Test24 mTest24;
    @Inject Test25 mTest25;
    @Inject Test26 mTest26;
    @Inject Test27 mTest27;
    @Inject Test28 mTest28;
    @Inject Test29 mTest29;
    @Inject Test30 mTest30;
    @Inject Test31 mTest31;
    @Inject Test32 mTest32;
    @Inject Test33 mTest33;
    @Inject Test34 mTest34;
    @Inject Test35 mTest35;
    @Inject Test36 mTest36;
    @Inject Test37 mTest37;
    @Inject Test38 mTest38;
    @Inject Test39 mTest39;
    @Inject Test40 mTest40;

    @Inject TestManager mTestManager;
    @Inject TestManager2 mTestManager2;
    @Inject TestManager3 mTestManager3;
    @Inject TestManager4 mTestManager4;
    @Inject TestManager5 mTestManager5;
    @Inject TestManager6 mTestManager6;
    @Inject TestManager7 mTestManager7;
    @Inject TestManager8 mTestManager8;
    @Inject TestManager9 mTestManager9;
    @Inject TestManager10 mTestManager10;
    @Inject TestManager11 mTestManager11;
    @Inject TestManager12 mTestManager12;
    @Inject TestManager13 mTestManager13;
    @Inject TestManager14 mTestManager14;
    @Inject TestManager15 mTestManager15;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        D2EComponent component = DaggerD2EComponent.builder().dagger2Module(new Dagger2Module()).build();
        component.inject(this);
        component.inject(mTest1);
        component.inject(mTest2);
        component.inject(mTest3);
        component.inject(mTest4);
        component.inject(mTest5);
        component.inject(mTest6);
        component.inject(mTest7);
        component.inject(mTest8);
        component.inject(mTest9);
        component.inject(mTest10);
        component.inject(mTest11);
        component.inject(mTest12);
        component.inject(mTest13);
        component.inject(mTest14);
        component.inject(mTest15);
        component.inject(mTest16);
        component.inject(mTest17);
        component.inject(mTest18);
        component.inject(mTest19);
        component.inject(mTest20);
        component.inject(mTest21);
        component.inject(mTest22);
        component.inject(mTest23);
        component.inject(mTest24);
        component.inject(mTest25);
        component.inject(mTest26);
        component.inject(mTest27);
        component.inject(mTest28);
        component.inject(mTest29);
        component.inject(mTest30);
        component.inject(mTest31);
        component.inject(mTest32);
        component.inject(mTest33);
        component.inject(mTest34);
        component.inject(mTest35);
        component.inject(mTest36);
        component.inject(mTest37);
        component.inject(mTest38);
        component.inject(mTest39);
        component.inject(mTest40);

        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest1.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest2.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest3.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest4.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest5.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest6.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest7.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest8.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest9.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest10.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest11.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest12.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest13.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest14.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest15.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest16.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest17.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest18.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest19.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest20.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest21.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest22.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest23.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest24.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest25.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest26.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest27.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest28.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest29.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest30.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest31.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest32.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest33.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest34.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest35.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest36.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest37.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest38.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest39.toString());
        Log.d(MainActivity.class.getSimpleName(), "onCreate(): " + mTest40.toString());

        mTestManager.start();
        mTestManager2.start();
        mTestManager3.start();
        mTestManager4.start();
        mTestManager5.start();
        mTestManager6.start();
        mTestManager7.start();
        mTestManager8.start();
        mTestManager9.start();
        mTestManager10.start();
        mTestManager11.start();
        mTestManager12.start();
        mTestManager13.start();
        mTestManager14.start();
        mTestManager15.start();

    }
}
